# Generated by Django 2.1.7 on 2020-01-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='y',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('F', 'First player to move'), ('S', 'Second player to move'), ('W', 'First player won'), ('L', 'Second player won'), ('D', 'Draw')], default='F', max_length=1),
        ),
    ]
